Update to support new object types in PHP 8.1
silverorange/MDB2_Driver_pgsql pull request #18
Opened 2022-06-10 19:58 UTC by gauthierm

Using `is_a` instead of `instanceof` so that we don't try to autoload a non-existent class in PHP 7.x.

2022-06-10 20:03 UTC, gauthierm commented on MDB2/Driver/pgsql.php
> +            && version_compare(PHP_VERSION, '5.2.0RC5', '>=')
I'm quite tempted to remove the PHP 5.2 support. I think we already declare the package requires 5.3+

2022-06-10 20:04 UTC, gauthierm commented on MDB2/Driver/pgsql.php
> +            && version_compare(PHP_VERSION, '5.2.0RC5', '>=')
I'm gunna do it!

2022-06-13 18:13 UTC, wittman commented
https://app.shortcut.com/silverorange/story/36731/update-to-support-new-object-types-in-php-8-1

2022-06-14 22:28 UTC, Qcode requested changes

2022-06-14 22:28 UTC, Qcode commented on MDB2/Driver/pgsql.php
> +        if (is_a($resource, 'PgSql\Result') || is_resource($resource)) {
```suggestion
        if (is_a($error, 'PgSql\Result') || is_resource($error)) {
```

2022-06-20 15:41 UTC, Qcode approved these changes

2022-06-20 15:41 UTC, merged